template:
  path: 'codepipeline/dmpworks.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !stack_output dev/codestar.yaml::CodestarConnectionARN

  S3ArtifactBucketId: !stack_output stg/s3.yaml::S3PrivateBucketID

  CodeBuildProjectName: !stack_output stg/codebuild/dmpworks.yaml::CodeBuildProjectId

  ChatbotConfigArn: !stack_output_external {{ var.chatbot_stack_output }}

  Env: !stack_attr sceptre_user_data.env

  AppName: "{{ var.project_code }}"

  RepositoryName: 'CDLUC3/dmptool-works-matching'

  BranchToMonitor: 'development'

  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'

dependencies:
  - stg/s3.yaml
  - stg/codebuild/dmpworks.yaml

capabilities:
  - CAPABILITY_IAM
  - CAPABILITY_NAMED_IAM