template:
  path: 'codepipeline/dmpworks.yaml'
  type: 'file'

parameters:
  CodeStarConnectionArn: !stack_output stg/codestar.yaml::CodestarConnectionARN

  S3ArtifactBucketId: !stack_output stg/s3.yaml::S3BucketID

  CodeBuildProjectName: !stack_output stg/codebuild/dmpworks.yaml::CodeBuildProjectId

  ChatbotConfigArn: !stack_output_external dmp-tool-stg-chatbot::SlackChannelConfigurationArn

  Env: !stack_attr sceptre_user_data.env

  AppName: "{{ var.project_code }}"

  RepositoryName: 'CDLUC3/dmptool-works-matching'

  BranchToMonitor: 'main'

  SourceOutputArtifactFormat: 'CODEBUILD_CLONE_REF'

dependencies:
  - stg/s3.yaml
  - stg/codebuild/dmpworks.yaml
