"""Shared default constants for dmpworks configuration.

Used by both the CLI (cli_utils.py) and the Lambda SSM config (scheduler/config.py)
to ensure consistent defaults and avoid drift.
"""

# DuckDB
DUCKDB_THREADS = 32
DUCKDB_MEMORY_LIMIT = "225GB"
DUCKDB_RELATIONS_DATACITE_THREADS = 16

# Crossref Metadata Transform
CROSSREF_METADATA_TRANSFORM_BATCH_SIZE = 500
CROSSREF_METADATA_TRANSFORM_ROW_GROUP_SIZE = 500_000
CROSSREF_METADATA_TRANSFORM_ROW_GROUPS_PER_FILE = 4
CROSSREF_METADATA_TRANSFORM_MAX_WORKERS = 32

# OpenAlex Works Transform
OPENALEX_WORKS_TRANSFORM_BATCH_SIZE = 16
OPENALEX_WORKS_TRANSFORM_ROW_GROUP_SIZE = 200_000
OPENALEX_WORKS_TRANSFORM_ROW_GROUPS_PER_FILE = 4
OPENALEX_WORKS_TRANSFORM_MAX_WORKERS = 32
OPENALEX_WORKS_TRANSFORM_INCLUDE_XPAC = False

# DataCite Transform
DATACITE_TRANSFORM_BATCH_SIZE = 150
DATACITE_TRANSFORM_ROW_GROUP_SIZE = 250_000
DATACITE_TRANSFORM_ROW_GROUPS_PER_FILE = 8
DATACITE_TRANSFORM_MAX_WORKERS = 8

# OpenSearch Sync
OPENSEARCH_SYNC_MAX_PROCESSES = 8
OPENSEARCH_SYNC_CHUNK_SIZE = 1000
OPENSEARCH_SYNC_MAX_CHUNK_BYTES = 100 * 1024 * 1024
OPENSEARCH_SYNC_MAX_RETRIES = 10
OPENSEARCH_SYNC_INITIAL_BACKOFF = 2
OPENSEARCH_SYNC_MAX_BACKOFF = 600
OPENSEARCH_SYNC_MAX_ERROR_SAMPLES = 50

# DMP Works Search
DMP_WORKS_SEARCH_QUERY_BUILDER = "build_dmp_works_search_baseline_query"
DMP_WORKS_SEARCH_SCROLL_TIME = "360m"
DMP_WORKS_SEARCH_BATCH_SIZE = 250
DMP_WORKS_SEARCH_MAX_RESULTS = 100
DMP_WORKS_SEARCH_PROJECT_END_BUFFER_YEARS = 3
DMP_WORKS_SEARCH_MAX_CONCURRENT_SEARCHES = 125
DMP_WORKS_SEARCH_MAX_CONCURRENT_SHARD_REQUESTS = 12
DMP_WORKS_SEARCH_INNER_HITS_SIZE = 50
DMP_WORKS_SEARCH_ROW_GROUP_SIZE = 50_000
DMP_WORKS_SEARCH_ROW_GROUPS_PER_FILE = 4

# SQLMesh
SQLMESH_INITIAL_RUN_ID = "INITIAL"

# Audits
AUDIT_CROSSREF_METADATA_WORKS_THRESHOLD = 167_008_747
AUDIT_DATACITE_WORKS_THRESHOLD = 72_019_576
AUDIT_NESTED_OBJECT_LIMIT = 20_000
AUDIT_OPENALEX_WORKS_THRESHOLD = 264_675_126
MAX_DOI_STATES = 3
MAX_RELATION_DEGREES = 100
