template_bucket_name: !ssm {{ var.ssm_prefix }}/dev/CloudFormationBucket

vars:
  env: dev

stack_tags:
  Environment: 'dev'

sceptre_user_data:
  ssm_path: "{{ var.ssm_prefix }}/dev"
  ecr_batch:
    name: dmpworks-dev-batch
    tag: latest
  ecr_lambda:
    name: dmpworks-dev-lambda
    tag: latest
