template:
  path: scheduler.yaml.j2
  type: file

parameters:
  Env: "{{ var.env }}"
  EcrImageUri: !ssm {{ stack_group_config.sceptre_user_data.ssm_path }}/LambdaEcrImageUri
  BucketName: !stack_output dev/s3.yaml::S3BucketID
  DataCiteCredentialsAPIUserSecretArn: !ssm {{ stack_group_config.sceptre_user_data.ssm_path }}/DataCiteCredentialsAPIUserSecretArn

dependencies:
  - dev/s3.yaml

capabilities:
  - CAPABILITY_IAM
