AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS Chatbot Slack notifications for CodePipeline'

Parameters:
  SlackWorkspaceId:
    Type: 'String'

  SlackChannelId:
    Type: 'String'

Resources:
  PipelineNotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Sub '${AWS::StackName}-notifications'

  ChatbotRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'chatbot.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-NotificationsOnly'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:GetMetricData'
                Resource: '*'

  SlackChannelConfiguration:
    Type: 'AWS::Chatbot::SlackChannelConfiguration'
    Properties:
      ConfigurationName: !Sub '${AWS::StackName}-pipeline-notifier'
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SlackChannelId: !Ref SlackChannelId
      SnsTopicArns:
        - !Ref PipelineNotificationTopic
      IamRoleArn: !GetAtt ChatbotRole.Arn

Outputs:
  SlackChannelConfigurationArn:
    Value: !GetAtt SlackChannelConfiguration.Arn

  PipelineNotificationTopicArn:
    Value: !Ref PipelineNotificationTopic